import assert from "node:assert/strict";
import { execFile as execFileCallback } from "node:child_process";
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { join } from "node:path";
import test from "node:test";

const execFile = promisify(execFileCallback);
const root = fileURLToPath(new URL("..", import.meta.url));

const goFixture = (runtimePath, store) => `package main

import (
    "context"
    "sync"
    "trace_runtime"
)

func leaf(ctx context.Context, label string) { _ = label }
func worker(ctx context.Context, wait *sync.WaitGroup, label string) { defer wait.Done(); leaf(ctx, label) }
func parent(ctx context.Context) {
    var wait sync.WaitGroup
    wait.Add(2)
    go worker(ctx, &wait, "a")
    go worker(ctx, &wait, "b")
    wait.Wait()
}
func main() {
    trace_runtime.Configure(trace_runtime.Config{Directory: "${store}", ProjectRoot: ".", Subsystem: "go-fixture"})
    parent(context.Background())
    trace_runtime.Reset()
}
`;

test("Go source instrumentation emits shared events, propagates contexts, excludes generated code, and is CLI-queryable", async () => {
  const directory = await mkdtemp(join("/tmp", "trace-go-"));
  const project = join(directory, "project");
  const store = join(directory, "store");
  try {
    await mkdir(project, { recursive: true });
    await writeFile(join(project, "go.mod"), `module fixture\n\ngo 1.22\n\nrequire trace_runtime v0.0.0\nreplace trace_runtime => ${join(root, "go/trace_runtime")}\n`, "utf8");
    await writeFile(join(project, "main.go"), goFixture(join(root, "go/trace_runtime"), store), "utf8");
    await writeFile(join(project, "generated.go"), "// Code generated by dependency; DO NOT EDIT.\npackage main\nfunc generated() {}\n", "utf8");
    const { stdout: generatorOutput } = await execFile("go", ["run", join(root, "go/cmd/tracegen/main.go"), "-root", project, "-runtime-import", "trace_runtime", "-write"], { cwd: root });
    assert.match(generatorOutput, /instrumented 1 files/);
    await execFile("go", ["run", "."], { cwd: project, maxBuffer: 1024 * 1024 });

    const files = (await readdir(store)).filter((name) => name.endsWith(".jsonl")).sort();
    const events = [];
    for (const file of files) events.push(...(await readFile(join(store, file), "utf8")).trim().split("\n").filter(Boolean).map(JSON.parse));
    assert.ok(events.some((event) => event.function === "parent" && event.event === "enter"));
    assert.equal(events.some((event) => event.function === "generated"), false);
    const workers = events.filter((event) => event.function === "worker" && event.event === "enter");
    const leaves = events.filter((event) => event.function === "leaf" && event.event === "enter");
    assert.equal(workers.length, 2);
    assert.equal(leaves.length, 2);
    assert.deepEqual(new Set(leaves.map((event) => event.parentInvocationId)), new Set(workers.map((event) => event.invocationId)));
    assert.equal(events.every((event) => event.language === "go"), true);

    const { stdout } = await execFile(process.execPath, [join(root, "bin/trace.mjs"), "past", "leaf", "--store", store], { cwd: root });
    const query = JSON.parse(stdout);
    assert.equal(query.mode, "past");
    assert.equal(query.targetReached, true);
    assert.equal(query.root.language, "go");
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
